### PR TITLE
Add first PTSM SMD terminal block (8 Positions)

### PR DESCRIPTION
**Pull request by svheymann**
First commit to check compliance. I will add the others with 2-7 positions if this one is ok.

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

we have a set of rules (KLC) that parts for this lib need to conform to. You can find them here:
https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention
We are currently also discussiong an extended version with more explanations: https://github.com/SchrodingersGat/kicad-library/wiki/KLC + Discussion about this: https://github.com/KiCad/kicad-library/issues/879

There's also a set of Python scripts that can check some of these rules automatically and even fix some problems: https://github.com/KiCad/kicad-library-utils

Now about your components:
First, here's the output of our scripts, please fix all tehse issues (let me know if you need help):
```
checking module: PhoenixContact_PTSM0,5_8-2,5-V_SMD
  Violating Rule 10.3
    Keywords are separated by spaces.
      Tags ('PhoenixContact PTSM 8 2,5mm vertical SMD spring clamp terminal block connector ') contains
      commas ','!

  Violating Rule 10.5
    Reference designator has a height of 1mm or smaller if needed, thickness of 0.15mm and is placed on
    the silkscreen layer.
      Reference label is on layer 'F.Fab', but should be on layer F.SilkS or B.SilkS!
      Reference label is on layer 'F.Fab', but should be on layer F.SilkS or B.SilkS!
      Reference label has a height of 2mm (expected: <=1mm).
      Reference label has a width of 2mm (expected: <=1mm).

  Violating Rule 10.6
    Attributes is set to the appropriate value, see tooltip for more information.
      There are mode SMD-pads (10) than THT-pads (0), but the attribute is not set to 'smd', but 'pth'.
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
      pin1 was found at x=-8.75mm y=3.2mm.
  Violating Rule 6.6
    Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
    center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
      No courtyard line was found at all.

    No courtyard line found in the module
  Violating Rule 6.9
    Fabrication layer contains an outline of the part using a 0.1mm line width.
      No drawings found on fabrication layer at all.
```

What's missing the most is an outline of the full connector on the F.Fab-layer!

Best,
JAN

**Comment by jkriege2** [comment]
PS: Also please add a datasheet link to the Doc-field.

**Comment by svheymann** [comment]
I think i got the first part.
But... i really cant find that doc-field in the footprint editor, where is it? Do you mean that description field?

**Comment by jkriege2** [comment]
Yes I think so ... sometimes they rename stuff ;-) Just reference, here's what I mean: 
2017-01-18 09_49_13-footprint editor no active library

BTW: The footprint looks very nice now! IMHO I would move the two text labels a bit closer (but that's not a must ;-)

And: Our check-script complains about the anchor position. It should be in the center of the SMD pad center-positions: (outside pads now at y=-1.58mm and lower pads at y=1.57mm):
2017-01-18 09_56_19-footprint editor no active library


Otherwise it  looks good to me!

best,
JAN

**Comment by svheymann** [comment]
So the vertical position has to be in the middle of the highest and lowest pad, same with left and right?

**Comment by jkriege2** [comment]
yes

**Comment by jkriege2** [comment]
additional comments:
1. please remove the comma from the keywords
2. please move the CrtYd onto an 0.01mm-grid (simply round in teh text file ;-) ...

Do you want to add the other variants to this PR or should I merge and you open a new PR? I would suggest adding to this!

JAN

**Comment by svheymann** [comment]
rounding was quite easy with vim ;)

**Comment by jkriege2** [comment]
OK!

this is fine now ... so add the others to this PR?
JAN

**Comment by svheymann** [comment]
Yes, coming soon.

**Comment by jkriege2** [comment]
OK, I'll wait until they are here then ;-)

**Comment by svheymann** [comment]
Done.

**Comment by jkriege2** [comment]
Great work!

Thanks,
JAN

**Pull request merged**
