### PR TITLE
Added GMSTBA-G series 7.5mm pin pitch connectors

### PR DESCRIPTION
**Pull request by poeschlr**
gmstba-g_7 5mm

### CODE REVIEW

**Comment by poeschlr** [comment]
gmstba-g_7 50

**Comment by pointhi** [comment]
the distance from the side pad to the end of the connector is wrong (x-direction)

Please check the drawings

**Comment by poeschlr** [comment]
I will check that tomorrow morning.

**Comment by poeschlr** [comment]
I think i might have the wrong order number(s) in this series.
Correct connector: 1766343 (in the footprint: 1766013)
https://www.phoenixcontact.com/online/portal/at?uri=pxc-oc-itemdetail:pid=1766343&library=atde&tab=1
I'm downloading the catalog right now. I will correct it within the next few minutes.

**Comment by poeschlr** [comment]
Order numbers are now corrected. (I looked in the wrong column when first typing them in.)

**Comment by pointhi** [comment]
thanks

**Pull request merged**
