### PR TITLE
Added GMSTBA-G series 7.62mm pin pitch connectors

### PR DESCRIPTION
**Pull request by poeschlr**
gmstba-g_7 62mm

### CODE REVIEW

**Comment by poeschlr** [comment]
gmstba-g_7 62

**Comment by pointhi** [comment]
the distance from the side pad to the end of the connector is wrong (x-direction)

Please check the drawings

**Comment by poeschlr** [comment]
Same as with #10 
Order numbers are now corrected. (I looked in the wrong column when first typing them in.)

**Comment by pointhi** [comment]
thanks for your contributions

**Pull request merged**
