### PR TITLE
Added MC-G series 3.50mm pin pitch connectors

### PR DESCRIPTION
**Pull request by poeschlr**
mc-g-3 5

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi @poeschlr,

Thanks for placing a screenshot here. Right off the bat, I can see you have a typo in the manufacturer name. Also, the pads should not be covered with silkscreen, as per KLC rule 6.5. Please run the check_kicad_mod.py script on your footprints to validate more rules. You can find it [here](https://github.com/KiCad/kicad-library-utils).

This also applies to all your other pull requests.

Regards,

Carl

**Comment by poeschlr** [comment]
@CarlPoirier 
Yes there is a typo in the manufacturer name. (I missed that it in two places.)

The KLC check script tells me that all non metric footprints violate rule 6.6 (I need to round the courtyard to 0.05mm.) No other violation is listed.

The silkscreen does not cover the pads. Is the distance between silkscreen and pads to small?
If so, how large should the gab between silkscreen and pad be?

Rule 6.5 is still violated because i don't have a marker for pin 1.  (I will add a small triangle to mark pin 1)

**Comment by CarlPoirier** [comment]
Even if the footprint has pads and such positioned at non-metric intervals, you can still set the silkscreen line width to 0.05mm. Also, your pads are definitely covered with silkscreen; they are the same color in the screenshot you have shown.

**Comment by poeschlr** [comment]
> Also, your pads are definitely covered with silkscreen

I don't know why i haven't seen that. (It is so obvious know, and i definitely made the conscious decision to add the F.SilkS layer to the pads.)

And the 6.6 violation is not because of the line width. From KLC:
This line is placed so that its clearance is measured from its center to the edges of pads and body, and its **position is rounded on a grid of 0.05mm.**

**Comment by CarlPoirier** [comment]
You can move the silkscreen outward to the next 0.05mm in this case.

**Comment by pointhi** [comment]
I would suggest to remove the `01x` from the footprints (because from what I see most series only have one row), and replacing the underscore with an x (to be consistent with the other footprints and the KLC:

```
PhonixContact_MC-G_01x02_3.50mm_Angled
```

to

```
PhoenixContact_MC-G_02x3.50mm_Angled
```

## 

https://www.phoenixcontact.com/online/portal/at?uri=pxc-oc-itemdetail:pid=1844210
https://www.phoenixcontact.com/online/portal/at?uri=pxc-oc-itemdetail:pid=1844223

I'm not familiar with phoenix contacts nominclatur, but it's always a good idea to have the full part name in the footprint name, which would result in something like:

```
PhoenixContact_MC-1.5/2-G-3.5_02x3.50mm_Angled
```

I think this has to discussed before applying changes.

**Comment by poeschlr** [comment]
Logic behind phoenix names (as far as i can tell):
MC 1,5/ 2-G-3,81 | MCV 1,5/ 2-G-3,81
- MC: Series MINI COMBICON
- MCV: Mini Combicon Vertical
- "1.5": I think it stands for the nominal cross section.
- First number (2 in the example): number of pins
- "G/GF": Header (from the german Grundgehäuse)/ Header with flange
- Second number (3,81): Pin pitch
- Further letters indicate modifications of the connector (Example HC: high current version)

I don't think a "/" could work within a file name. (Used as path separator in linux)
we could replace it with "_" or "-"
So the possible names could be:
- PhoenixContact_MC-1.5_2-G-3.5_02x3.50mm_Angled
- PhoenixContact_MC-1.5-2-G-3.5_02x3.50mm_Angled
- PhoenixContact_MC-G_02x3.50mm_Angled
- PhoenixContact_MC-1.5-G_02x3.50mm_Angled

**Comment by poeschlr** [comment]
@CarlPoirier 
I'm a bit confused now. According to KLC only the courtyard should be rounded to a 0.05mm grid.
Should i also round the silkscreen position?
(The footprints are script generated, the outer dimension is calculated based on number of pins and pin pitch. To get the right behavior i need to round this result to the nearest 0.05)

Another clarification:
Should i always round up (Distance from part to courtyard is at least 0.5mm and maximal 0.549)
or should i round to the nearest 0.05 (Distance can be as low as 0.476)
I would interpret the KLC as meaning the later of the two.

**Comment by poeschlr** [comment]
Quick update: I have added a marker for pin 1, removed silkscreen from pads, rounded courtyard to 0.05mm grid and included an offset for the silkoutline such that it is completely outside the body.
Screenshots (From some of the footprints.)

screenshot from 2016-07-11 20-27-21
screenshot from 2016-07-11 20-27-49
screenshot from 2016-07-11 20-28-39
screenshot from 2016-07-11 20-29-00
screenshot from 2016-07-11 20-29-27

As soon as the naming is decided, i will update the footprints in all pull requests. I will then also include new screenshots in all requests.

**Comment by Schlumpf** [comment]
I propose to make the pin 1 rectangular. Then it would be possible to detect pin 1 on PCBs without silkscreen.
And, is it correct to have the pin 1 marker outside the courtyard?

**Comment by poeschlr** [comment]
Yes the Marker is outside the courtyard. The KLC defines that the courtyard has to be outside of pads and body. 
I don't really see the benefits of rectangular pads for pin 1. As soon as the pcb is soldered you can't easily see the pad shape.

**Comment by pointhi** [comment]
I also think pad 1 should be rectangular. For PCB's without silkscreen this would be pretty helpful (and to find pad 1 at the bottom of the pcb more easily)

**Comment by poeschlr** [comment]
Pad 1 is now rectangular,
I also renamed the footprints. (removed 01x from the name as suggested by pointhi. Option 3 from my post)
I will update the files of the requests within the next hours
Screenshots:
screenshot from 2016-07-19 12-17-19
screenshot from 2016-07-19 12-21-47
screenshot from 2016-07-19 12-22-20
screenshot from 2016-07-19 12-23-13
screenshot from 2016-07-19 12-23-43

**Comment by poeschlr** [comment]
mc-g_3 50

**Comment by pointhi** [comment]
@poeschlr 
- From what the kicad team discussed some time ago, all connector footprints should contain the keyword `connector`: https://github.com/KiCad/kicad-library/issues/368#issuecomment-177514422

@CarlPoirier do you see outstanding issues which have to be fixed on all footprints? I think the general questions are solved, and I should now be able to start reviewing/merging the individual series.

The missing `connectors` keyword could be fixed by me after merging the footprints.

**Comment by CarlPoirier** [comment]
@pointhi I will be checking it this morning, hold on.

**Comment by CarlPoirier** [comment]
The rest seems good to me. I'll let you decide if you wait for the `connectors` keyword or add it afterwards.

**Comment by pointhi** [comment]
thanks for your great contribution

**Pull request merged**
