### PR TITLE
Added Footprints for MSTB and MC Series Connectors.

### PR DESCRIPTION
**Pull request by poeschlr**
All footprints are generated via the footprint generator script by Thomas Pointhuber (https://github.com/pointhi/kicad-footprint-generator)

3D shape (step and wrl) files will follow.
Generated via easyw's cadquery scripts (https://github.com/easyw/kicad-3d-models-in-freecad)
MSTB Series 3d files are already finished.
MC files should be done within the next week.

### CODE REVIEW

**Comment by pointhi** [comment]
Thanks for your greate contribution.

I would suggest you to split this Pull Request, otherwise reviewing would be pretty complicated. The easiest (because smallest set of footprints per Pull Request) would be one Pull Request per serie and alignment. Adding an image would also be helpful, but I could do that part for you if you like.

**Comment by poeschlr** [comment]
Ok i will split the request into multiple requests.

**Comment by poeschlr** [comment]
I just realized that i have the naming of the mstb series wrong. 
(There are two different types starting with MSTB. There is MSTB-xxxx-G and MSTB-xxxx-GF. I don't have footprints for the MSTB-xxxx-G series, thats the reason i didn't realize this until now.)
I will fix that until tomorrow.

**Comment by poeschlr** [comment]
Splitting is done. I close this request.

**Pull request closed without merging**
