### PR TITLE
[enh] Changed ?MSTB?? series connectors for complience with KLCv1.2

### PR DESCRIPTION
**Pull request by poeschlr**
Series changed: GMSTB, GMSTBV, MSTB, MSTBA, MSTBV and MSTBVA 

Added f.fab and b.fab outline (fab for back side only for footprints with mounting screws.), 
second reference on fab layer, 
Pin 1 marker on fab layer, 
courtyard grid 0.01mm

Footprints are generated with the python script framework by @pointhi
https://github.com/poeschlr/kicad-footprint-generator/tree/better-phoenix-scripts

Used KLC version: https://github.com/SchrodingersGat/kicad-library/wiki/KLC
As suggested by @SchrodingersGat in pull request: KiCad/Connectors_JST.pretty#31

Silkscreen details for people who hand populate their boards (or at least the THT components of their boards)

I'm not 100% happy with the pin 1 markers in this series, but i don't have a better idea how to make them. Suggestions?

Should footprints with mounting screws have a courtyard at the back? (If so how should it look like. I would at least make a circle around the mount screws with the same offset as the courtyard on the front.)

New footprints. (Only one screenshot per series.)
screenshot from 2017-02-20 18-22-40

screenshot from 2017-02-20 18-22-58

screenshot from 2017-02-20 18-23-07

screenshot from 2017-02-20 18-23-15

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
These footprints look great!

1. I like the idea of having courtyard on the back, marking the location of the mounting holes. I would have at least 0.5mm clearance around the largest dimension of the hole.

2. I don't mind the pin-1 indication, it's a harder footprint to make one for especially due to the larger pitch. The only other option I can think of is like so:

capture

**Comment by SchrodingersGat** [comment]
I think I like yours more. You could move the arrow closer to the actual connector and that would save some room...

**Comment by poeschlr** [comment]
Added the courtyard around the mounting screws. (only footprints with mounting screws)
Pin 1 marker on silk screen is now a bit closer to the connector. (all connectors in this pull request)

I also fixed my tags. (added spaces between keywords and added the connector keyword.)
The mounting screw details are now documented in the doc field. (only footprints with mounting screws)

screenshot from 2017-02-21 15-06-10

screenshot from 2017-02-21 15-06-54

**Comment by SchrodingersGat** [comment]
This is fantastic work, thanks :)

**Pull request merged**
