### PR TITLE
Added MCV-GF series 3.81mm pin pitch connectors with mount holes

### PR DESCRIPTION
**Pull request by poeschlr**
mcv-gf-3 81-mh

### CODE REVIEW

**Comment by poeschlr** [comment]
mcv-gf_3 81-mh

**Comment by pointhi** [comment]
the datasheet says 1.4mm drill size: https://www.phoenixcontact.com/online/portal/de?uri=pxc-oc-itemdetail:pid=1830648

**Comment by poeschlr** [comment]
Where did you see that? On the technical details side of this connector it says drill size (bohrdurchmesser) = 1.2mm
screenshot from 2016-07-24 21-25-54

**Comment by pointhi** [comment]
Under Technical Plan -> Drillplan in the linked url. Probably a error made by phoenix contacts, because all other footprints were 1.2mm

There are for example footprints with the suffix P26, which have 1.4mm drill size. Probably they used the file from this place.

**Comment by poeschlr** [comment]
Yes you are right, in this drawing there is the drill size stated as 1.4mm. 
If i remember correctly the paper catalog has 1.2mm in its drawing. The catalog is at the university, i could check that tomorrow.

**Comment by pointhi** [comment]
I also think it's 1.2mm, because the table says so, and all other footprints of this series had 1.2mm

**Comment by poeschlr** [comment]
In the catalog, the metric (3.5mm) and imperial (3.81mm) pin pitch versions have the same drawing.
The 3.5mm version has 1.2mm in the drawing on the homepage.
https://www.phoenixcontact.com/online/portal/at?uri=pxc-oc-itemdetail:pid=1843224&library=atde&pcck=P-11-02-11&tab=1
So i'm convinced, that this one picture on the webside is wrong.

**Comment by pointhi** [comment]
I think we can safely assume they put the wrong drawing on the website.

I'm really wondering how much time you put into creating those footprints. They are perfectly made, and every one has the correct order number attached. As little Fact, after merging all Footprints of you, they would cover about 1/3 of all manufacture specific connectors currently present in KiCad.

I'm and @SchrodingersGat worked pretty long to get about 300 JST Footprints into KiCad.

**Comment by poeschlr** [comment]
The phoenix connectors i added are all quite similar. As soon as i understood your footprint generator script, it wasn't that much work. I think about two to three days for the first implementation. Plus less than two days for the pull requests and implementation of all changes. 
(I was able do reuse a lot of code from the mstb series for the mc series.)

**Pull request merged**
