### PR TITLE
Fix pad to pad clearance

### PR DESCRIPTION
**Pull request by poeschlr**
This pull request fixes the pad to pad clearance of the MSTB and GMSTB series connectors.
(Fix for issue https://github.com/KiCad/Connectors_Phoenix.pretty/issues/47)

Changes

- For MSTB 5.00mm pin pitch versions: reduced pad size in x direction from 2.1mm to 2.0mm (pad to pad clearance = 5.0 - 2.0 = 3.0mm; Resulting annular ring = 0.3mm)
- For MSTB 5.08mm pin pitch versions: reduced pad size in x direction from 2.1mm to 2.08mm (pad to pad clearance = 5.08 - 2.08 = 3.0mm; Resulting annular ring = 0.34mm)
- For GMSTB 7.5mm pin pitch versions: reduced pad size in x direction from 2.1mm to 2.0mm (pad to pad clearance = 7.5 - 2 = 5.5mm; Resulting annular ring = 0.3mm)

### CODE REVIEW

**Comment by poeschlr** [comment]
Do not merge. Somehow i exported it with the wrong settings for silk screen width. I will take a look at it tomorrow.

**Comment by poeschlr** [comment]
Should now be ready to merge.

Sadly the description field changed for a few connectors because python 3 seems to handle dicts differently compared to python 2.

After this PR is merged i will create a second pull request that add ${KSYS3DMOD}/ to the 3d files path of all connectors. This second pull request will then change the description field of the remaining connectors such that the ordering information is sorted by rated current for all parts. (originally i did not sort the dict, python seems to decide for it self what order the dict will have)

**Comment by SchrodingersGat** [comment]
I believe that OrderedDict datatype in python obeys insertion order, if that helps.

**Comment by SchrodingersGat** [comment]
Thanks for your work Rene

**Comment by poeschlr** [comment]
Good to know.

**Pull request merged**
