### PR TITLE
Added MSTBV-GF series 5.08mm pin pitch connectors with mount hole

### PR DESCRIPTION
**Pull request by poeschlr**
mstbv-gf_mh_5 08mm

### CODE REVIEW

**Comment by poeschlr** [comment]
mstbv-gf_5 08_mh

**Comment by pointhi** [comment]
the inner silkscreen ring which marks the mounting hole is useless

**Comment by poeschlr** [comment]
This ring does exist in all footprints.
I would suggest, to merge all footprints into master.
After that we can remove this ring from all footprints in one go. (Copying the footprints for each pull request separately is a lot of work.) This can be done within the script. Maybe only remove it from footprints with mounting holes.

**Comment by pointhi** [comment]
yep, it's enough to delete them only on footprints with mounting holes

**Comment by poeschlr** [comment]
We can also add the connector keyword at the same time.

**Comment by poeschlr** [comment]
As soon as everything is merged i will open a new pull request with this two changes.

**Comment by pointhi** [comment]
ok

**Pull request merged**
