### PR TITLE
Add dual row MDSTB 5mm angled PCB headers

### PR DESCRIPTION
**Pull request by svheymann**

### CODE REVIEW

**Comment by poeschlr** [comment]
Please fill out the 3d settings (Add the path such that if we get a 3d model later on we do not need to change the footprint)
  - Path: $KISYS3DMOD/Connectors_Phoenix/[footprint_name].wrl
  - scale (1,1,1)
  - offset (0,0,0)
  - rotation (0,0,0)

Only the pad with pin number 1 should be a rectangle
The pin 1 markers should either point to pin 1 or be removed.
The documentation field needs the correct information. Currently you have the information of the MSTB connector you copied.

Do you have an order number for these connectors? The once i found when i search for MDSTB on the webside look rather different. (Example [part with order number 1938948](https://www.phoenixcontact.com/online/portal/at/pxc/product_detail_page/!ut/p/z1/3Vjfc6IwEP5X7INvjQm_4WbuwWKrbU_HVq2FFyYJweYOxAJq27_-gtqrZ6fQG4-H4mQMSb79NrvZTQLQhffQneMVn-GMx3Mcirbj6p4pX9u9rir1uxe2jNq3veGFfTPojoYqnBYCRjp0Px5WDLlE3laL5N_0ow9-bVQmfwdd6GaYQEfKnxaU_oLOEEgSQLL4z_tCThKcPEMHZz7bgLgv4JZiWqqZt-NgaNvXh2IZz0IGnW6ynPsh42nGGqDR74zGZw35VGuihgy6EtBOkSn6X9mmuWSJQzaAIosLGcSSjHzmtcfe8N5uj6EjHGh8iG5LcLribA0n8ziJRECMtl7KPYB9Q8NBoIKAEgmoMmPAMgwfEJ8oxFKRpWAL9lCJhht0pIYSerlaeuVI-qvCxbpU8gzkPx8f3TZ0aTzP2FMG7_NAbKI1I030EEeseI7KoMjDUsCoaTIgEzFR1ZQ0YCJVBqaERThqloF1WkYvV0p_US39XbXOuZOOpL8q20BL4iMOgl13E6UMJ_TBS1i6DA-buSJOotaaRi3UWjzR1ptk6y-kt8Az9t_UlsSWsnUYjxYhpzzrxz4LoZMly81GjGl-TEFnS1mSqpqxc74fhHg-W-ZWOJuOOOVbnryVMMr4iiW7sU-dB0nsLzdTGed-cA6OFD-IxLR3fAdHx060wzLMw_QyY9HlHqDYoB9q3QzS62aQVjeD6pZDnbrlUKduOdSpWw516pZD47qF3Lhum8JYqZlBCvpyBgnAMuHQEVdrEFPAxbC_QX4TPN9fUe9u4TtSb4v91N07wnzeRDvBtIlCnm4v7eJ5aJ95QmbOaBYnqffmjCbyqWaKVw4DEE1FQNV1HWAZqYAxRSZ6YEiKVbYsE63gbSe3kDAFqMz3Bb0v6CXZAIHBjEDDjFJLKqM3KqWX1ErpexXTV-scS6-W_tjZF39HOZeOSZoFJftJs_jXpFlEk8kkMpVt0W976_U4eJhFXv9c0fIqM0VHZJP9agpcoi1WA4DJC9srQfSHaVtykLZXvoAAI-az8nI2AM7V6n3lOu2Tk9_YymJU/?uri=pxc-oc-itemdetail:pid=1938948&library=atde&tab=1))

Edit: ok i think i found the one you based the footprint on. Is it [1762062](https://www.phoenixcontact.com/online/portal/at/pxc/offcontext/search_result_page/!ut/p/z1/3VhJc-I4FP4rmYNvLSTLe6rmQJsG0umk6AAh9oWSZBk844XYApL-9SMDSRg6sWeK9qFNqdDi97636D1t0IcP0E_JJloQEWUpiWXf8825ja_d4UBXbwZ9F6Pu3XDUd7_fDjQLw1kVwXhsQv8cflf_b_zog18X1fHfQx_6glDoqWVrxdjf0BsBVQUIy_9yLI5oTvJn6BER8B1RFEhyWzccpJf9LBy57vUpm4hEzKF30xtPPl_gT4aCMAIDFRifkH0x8C7AxQvErCSv8cKOoMrMSgQ5D-OAz7uT-ejB7U6gJ71mfUjdVeFsE_EtnKZZnsgoGO9dU5pNAssgYaiDkFEV6Jhz4FhWAGhANeroyNGIA4eoRsJ3dKaEGnjcLLx2JvzXysm60sq0i_56fPS70GdZKviTgA9l9Cloy6mCllnCq3XUbqs8rIac2TYHmEpFdVs1gI10DGyVOLptOBYxWR08bhS-3yz8fbPOuVfPhP9at2rVxEcWhodhBRWc5Gw5z3mxjk-7paCIJp0tSzqos3pinTfOzr8o5yuy4L9MbE1saXuHPUIvCQpBD4vnu0sxYeVGBb1CkFzMIrEckZwkXPC8KD-v8wh60i6wl38p1SwiUZM7Y8M6zFgQxiRdrEvTvd1AJrl38spezhmPNjw_fNvtHO_vF3kWrHeKTkqXeSdbThAmWfAi4WRrObD2uCBRXFwJnlwdEVSb8U1vhxlmO8ww2mFGO3Kj147c6LUjN3rtyI1eO3Jj0o6gmrQjxSdaK8zQ0G9ixvGpMWNAnhaTYEd5KXH-fKH66eB8AJ3vaT8-Livo6MCckChV0IG1UBBPRf684z1ulzjdlGr2ovRPyHOed9Z5DB-WQqyKSwUpaCFPvmvaYVmioOvIJYGC3CxNORNZXsxHy4yn0ZPUkQvxLAWu41hBuvke8DIrpJZveDXTOjUqrjqOZjuUa0DnQQB0MzABUbEFQotboUE4Y45aB281Cq_qjcIPG4Zv1jmO2Sz8udpXP6J8Uetuq6fJF0fF_por2ytG5-wtgVavD3sKCphhy0u6BaihI6mbKXXDSAeca5iaoaVqjl1j-l1FXMgFButhgIFhBhTohqUBm4UmQBIac9PmGFl18Gaj8Faz2ltao_BV72K_Al5tFL7frPb9c7WvzsnP-P_m5Acb4iqZTqeJre2LeTfcbifhcpHMb75oRlkJWw4kLj2uZsCnxmpza2xuAaE_-FEJk1ewfTnQvZbfgIFT-1mLN9_CFx_8VMWbE4-c-Kf7xz8_sxRw/?uri=pxc-oc-itemdetail:pid=1762062&library=atde&pcck=P-11-02-11&tab=1)?

**Comment by evanshultz** [comment]
@svheymann Will you be able to review the comments above and finish this PR soon?

**Comment by svheymann** [comment]
I had some other stuff going so it took me some time to return to this. I did not realize that it is that urgent as the first review also took some weeks.
I am going to do the changes maybe this weekend or beginning of next week.

**Comment by evanshultz** [comment]
@svheymann No great urgency, I was just reviewing open PRs in an effort to organize. Thank you!

**Comment by svheymann** [comment]
done.
The part numbers are correct, mine are the 5mm version, yours are the 5.08mm version

**Comment by poeschlr** [comment]
Could you have a look at issue https://github.com/KiCad/Connectors_Phoenix.pretty/issues/47
This will apply to your footprint as well. (I needed to change the y size of my pads to ensure 3mm pad to pad clearance.)

**Comment by svheymann** [comment]
done.

**Comment by poeschlr** [comment]
For the 2x3 connector the pin 1 marker on the fab layer is at pin 4.
For connector footprints the courtyard should have a clearance of 0.5mm measured from the fab outline.

What symbol are you intending to use for this connector? 
The conn_02x?? symbols of the official lib have a different pin number ordering then you chose here.
I'm not even sure that these symbols would be the best choice for such connector types.

Maybe it would be a good idea to use a multi unit symbol and use pin numbers of the type A1, A2, A3, ... B1, B2, B3, ...
@SchrodingersGat, @jkriege2, @evanshultz, @hackscribble, @Shackmeister What do you guys think about that? (As soon as a decision on that is made i would volunteer to make the symbols.)

**Comment by poeschlr** [comment]
The 3d model path should have the prefix ${KISYS3DMOD}/
This way the users can easily change the storage location of their 3d models.

**Comment by evanshultz** [comment]
I'm good using the `Conn_02*` symbols for this footprint. Otherwise, we break the paradigm of having division between symbols and footprints. The footprint does look like two rows of pins.

**Comment by svheymann** [comment]
Courtyard: here i was told it should be 0.25mm: [fuses](https://github.com/KiCad/Fuse_Holders_and_Fuses.pretty/pull/10)
Which one should i use now?

**Comment by svheymann** [comment]
pin numbering: i really was not sure how to number them. My thought was, that the lower rank is used first from left to right. e.g. if you connect some 230V-Device, you would put L/N/PE on one connector in the first rank and then again L/N/PE on the second. So i thought it would be more intuitive if those are numbered in one line.

But anyway, how should i number them?

**Comment by poeschlr** [comment]
For now i would suggest we make this footprints are compatible to the conn_02x02 and conn_02x03 symbols. (It is not ideal but i think the best option that is available in the current library system.)

So i would use the following pin numbering scheme:
screenshot from 2017-07-08 14-18-58

**Comment by poeschlr** [comment]
@svheymann we now have new connector symbols that would benefit this footprint.

I would suggest the use of a symbol that has a letter to indicate the row plus a number that indicates the pin in this row. (I would use Conn_02x??_Row_Letter_First)
screenshot from 2017-08-24 10-58-37

**Comment by svheymann** [comment]
ok, i will change that. I am currently on vacation and will make a commit in about 2 weeks.

**Comment by poeschlr** [comment]
@svheymann if you are still interested, please reopen this in the new [kicad-footprint](https://github.com/KiCad/kicad-footprints) repo.
This repo is now declared legacy in preparation for the kicad v5 release.

**Pull request closed without merging**
