### PR TITLE
[enh] Changed MC and MCV series connectors for complience with KLCv1.2

### PR DESCRIPTION
**Pull request by poeschlr**
Added fab outline, 
second reference on fab layer 
Pin 1 marker on fab layer 

Footprints are generated with the python script framework by @pointhi
https://github.com/poeschlr/kicad-footprint-generator/tree/better-phoenix-scripts 

Used KLC version: https://github.com/SchrodingersGat/kicad-library/wiki/KLC
As suggested by @SchrodingersGat in pull request: https://github.com/KiCad/Connectors_JST.pretty/pull/31

New footprints. (Only one screenshot per series.)
screenshot from 2017-02-20 14-58-46

screenshot from 2017-02-20 14-59-05

screenshot from 2017-02-20 14-59-15

screenshot from 2017-02-20 14-59-32

### CODE REVIEW

**Comment by poeschlr** [comment]
The current footprint check has a violation of rule 6.6 (courtyard) because of my pin 1 marker on the fab layer.
(Only MCV series.)

**Comment by jkriege2** [comment]
Hi!

just a suggestion on your footprints: I would put the details of the package (e.g. the inner "complicated" drawing in MCV) onto the F.Fab layer, as it won't be visible after assembly anyways ...

Best,
JAN

**Comment by poeschlr** [comment]
@jkriege2 
I think there was a discussion about that a few years ago with the outcome that it is undesirable to have that much detail on the fab layer. 
Also this details on the silk layer are mainly for the people who populate the pcb by hand. (This way it is easy to see which way the connector should be placed.)

**Comment by poeschlr** [comment]
Should there be a courtyard around the mounting screw heads on the bottom? (only footprint versions who have this feature.)

**Comment by poeschlr** [comment]
Added the fab layer to the mount screws on the bottom.
screenshot from 2017-02-20 18-36-32

screenshot from 2017-02-20 18-36-50

**Comment by poeschlr** [comment]
Added the courtyard around the mounting screws. (only footprints with mounting screws)
Pin 1 marker on silk screen is now a bit closer to the connector. As suggested in #45. This only affects angled connectors.
I also fixed my tags. (added spaces between keywords and added the connector keyword.)
The mounting screw details are now documented in the doc field. (only footprints with mounting screws)
screenshot from 2017-02-21 14-30-12

screenshot from 2017-02-21 14-34-32

**Comment by SchrodingersGat** [comment]
These look great, thanks for the hard work.

I agree that detail for connectors like this should be on Silk not Fab. Perhaps this needs to be clearly specified in KLC.

**Pull request merged**
